### ISSUE TITLE
5.0.0-alpha bug

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid-enterprise#35] opened 2016-06-23 12:17 UTC
Throwing in console:

> Uncaught TypeError: Cannot read property 'getActualWidth' of undefined
> in method `MoveColumnController.prototype.getNewIndexForColMovingRight`

Not changing the experience or anything, just spamming console

**Comment by ceolter** [comment] 2016-06-23 12:19
how to reproduce?

**Comment by ceolter** [comment] 2016-06-23 12:19
i can move columns fine on my demo page, without this error appearing

**Comment by AmitMY** [comment] 2016-06-23 12:37
Have a grid, then move to pivot mode, and try to drag a column onto the grid, from the panel.
throws hundreds of those..

Another problem I experience, is when going in to pivot, then back, the table shows the columns, but no rows, even though there were rows before.

If you can't reproduce, Ill make a plunker in the next few days..

**Comment by ceolter** [comment] 2016-06-23 12:44
i can reproduce when i try to drag in a columns that should not be visible, because the column group it is in is closed.

```Another problem I experience, is when going in to pivot, then back, the table shows the columns, but no rows, even though there were rows before.```
-> for pivot to make sense, you need at least one group or pivot active, groups work by themselves, pivots also require a value.

**Comment by AmitMY** [comment] 2016-06-23 13:21
I meant - `going in to pivot, then back` - going to pivot mode, then back to normal mode, and it happens only sometimes...

It is great you can reproduce the first one. I think it makes sense, but should not through an error

**Comment by ceolter** [comment] 2016-06-23 13:26
re first one, yea makes sens, but it's happening in the last release also, not a new bug, so i'm not very worried.

re second one, if you had steps to reproduce from one of the documentation examples that would be great.

**Comment by ceolter** [comment] 2017-01-20 13:34
this still an issue Amit?

**Comment by ceolter** [comment] 2017-01-20 13:35
am doing aggressive closing today, if an issue, please reopen :)

**Closed by ceolter** 2017-01-20 13:35 UTC
