### ISSUE TITLE
Resizers not working properly on right pinned columns

### ISSUE THREAD

**Issue by iboffa** [ceolter/ag-grid-enterprise#122] opened 2017-04-06 08:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

On right pinned columns, first resizer is missing, so that the resizers on pinned columns work on the previous column
**Expected behavior**

The resizer should work on the same column

**Minimal reproduction of the problem with instructions**

Unfortunately I cannot replicate the bug on plunker. I tried to copy-paste my code but I don't have the same issue. I attached an image showing that only one resizer is available
![missing_resizer_ag-grid](https://cloud.githubusercontent.com/assets/24269444/24745975/d4b7f90a-1ab7-11e7-8ae5-f56b36162801.PNG)

**What is the motivation / use case for changing the behavior?**

Right pinned columns should resize correctly

**Please tell us about your environment:**

Windows 10, Apache Server 8.5.6, Eclipse Neon

* **ag-Grid-Enterprise version:** 9.0.0

* **Browser:** [ Chrome 57 | Firefox 48 | IE 11  ]

* **Language:** [ES5]

**Comment by seanlandsman** [comment] 2017-04-06 16:42
Hi

I've spent some time trying to reproduce this but I'm afraid so far I've been unable to. If you can point to an example we have online where this happens, or where you can provide something for us to look at then that will help.

thanks

**Comment by seanlandsman** [comment] 2017-04-18 09:20
Hi

Closing this as we are unable to reproduce

**Closed by seanlandsman** 2017-04-18 09:20 UTC
Labels: needs_repro
