### ISSUE TITLE
allowing filtering of columns in tool panel

### ISSUE THREAD

**Issue by alhweiti** [ceolter/ag-grid-enterprise#73] opened 2016-09-21 21:00 UTC
Hi there,
We implemented ag-grid in a solution, and we have a really long list of columns (>800)..we're looking into implementing a filter textbox for columns in the toolpanel, what is the best way to do this? 

Ahlam

**Comment by ceolter** [comment] 2016-10-11 09:32
having a filter textbox for the columns is not something we have thought about. if you want this - then the only way really is to build your own toolpanel.

i'll keep this open - we do review the issues and this is an interesting idea.

**Comment by ceolter** [comment] 2017-01-20 13:38
duplicate of this:
https://github.com/ceolter/ag-grid/issues/643
closing

**Closed by ceolter** 2017-01-20 13:38 UTC

**Comment by tasinsahin** [comment] 2017-09-28 14:52
How can I achieve to build my own toolpanel? Could you give me an idea?
