### ISSUE TITLE
Horizontal scrolling is 'glitchy' in Chrome Canary

### ISSUE THREAD

**Issue by hunthunthunt** [ceolter/ag-grid-enterprise#3] opened 2016-04-01 14:08 UTC
Using Chrome Canary (Version 51.0.2695.0 canary) on Mac OSX 10.10.5 horizontal scrolling is 'glitchy'. 

Horizontal scrolling is fine in Firefox and Chrome (Version 49.0.2623.110).

**Comment by ceolter** [comment] 2016-04-01 14:12
Hi Anthony, testing on Windows 10 and Chrome Canary, it's working all fine. I tested using the main on-line demo.

How many columns do you have?

Any idea on your end why it is happening? (given I can't reproduce here)

Do you want to buy me a Mac?

**Comment by hunthunthunt** [comment] 2016-04-01 14:22
@ceolter 

I actually just tested this on other sites and it seems that the issue is with Canary on mac in general. Canary is too aggressively interpreting the left scroll as a 'browser back' (an OSX feature).

**Comment by ceolter** [comment] 2016-04-01 14:23
great, thanks. we can close this then?

**Comment by ceolter** [comment] 2016-04-01 14:23
you missed the last 36 birthdays, send the mac on now, i'll get a list together with the other 35 items :)

**Closed by ceolter** 2016-04-01 14:23 UTC
