### ISSUE TITLE
Angular 1.X Scope Based Child Grid not getting destroyed (Memory Leak)

### ISSUE THREAD

**Issue by ananddc1989** [ceolter/ag-grid-enterprise#84] opened 2016-11-03 09:47 UTC
I have implemented the scope based master details grid to achieve the angularCompileRows: true in the child grid, this.MD will be unique ID

```
DetailPanelCellRenderer.prototype.destroy = function () {
                console.log($scope["detailGridOptions" + this.MD])
                if ($scope["detailGridOptions" + this.MD].api !== null)
                    $scope["detailGridOptions" + this.MD].api.destroy();
                else
                    delete $scope["detailGridOptions" + this.MD];
            };
```

![](https://cloud.githubusercontent.com/assets/3772663/19918696/7d157242-a0f3-11e6-89a7-194839740f39.png)

So destroy method not happening due to api is null while collapse, But JS based sub grid have api.
This Leading the Memory Leak

![](https://cloud.githubusercontent.com/assets/3772663/19918747/d8e28d9e-a0f3-11e6-9000-df61a4d626f4.png)

Grid Objects still in memory because destroy not happen, Please provide solution !

Thanks

**Comment by ananddc1989** [comment] 2016-11-03 09:49
@ceolter , @seanlandsman ,

Can you help me out of this issue any one? sub grid is working fine with scope, but unable to destroy the api, because its null in destroy method, i haven't found any sample for angular 1.X edition for master detail grid. this is case is happen not only sub grid, 

  ```
//#region Destroy
            $scope.$on("$destroy", function () {
                console.log($scope.myGridModels)
                if ($scope.myGridModels.api !== null)
                    $scope.myGridModels.api.destroy();
                $scope.myGridModels = null;
            });

 //#endregion
```

Controller destroy method also,

**Comment by seanlandsman** [comment] 2016-11-03 12:40
Hi - if you are using the enterprise version of ag-grid, please post your question on the enterprise forum: https://ag-grid.com/forum

**Comment by seanlandsman** [comment] 2016-11-03 12:43
I see that this is a duplicate of https://github.com/ceolter/ag-grid/issues/1234 - closing this one, we'll take a look at the other issue

**Closed by seanlandsman** 2016-11-03 12:43 UTC
